-- Health Information Companion — seed data (GENERATED by scripts/seed.ts --sql).
-- Do not edit by hand; re-generate. Run AFTER schema.sql. Idempotent (safe to re-run).
-- This is the cleaned + de-duplicated content: 24 source rows → 20 articles.

begin;

-- Topics found in the data (English labels). schema.sql already seeds these;
-- included for resilience if the content team introduces a new topic.
insert into topics (slug) values
  ('malaria'),
  ('maternal-health'),
  ('nutrition'),
  ('hygiene'),
  ('clean-water'),
  ('first-aid'),
  ('immunisation'),
  ('family-planning')
on conflict (slug) do nothing;

insert into topic_translations (topic_slug, language_code, label) values
  ('malaria', 'en', 'Malaria'),
  ('maternal-health', 'en', 'Maternal Health'),
  ('nutrition', 'en', 'Nutrition'),
  ('hygiene', 'en', 'Hygiene'),
  ('clean-water', 'en', 'Clean Water'),
  ('first-aid', 'en', 'First Aid'),
  ('immunisation', 'en', 'Immunisation'),
  ('family-planning', 'en', 'Family Planning')
on conflict (topic_slug, language_code) do nothing;

-- Articles (language-neutral rows).
insert into articles (id, slug, topic_slug, status, author, source_updated_at) values
  (1, 'sleeping-under-a-treated-net', 'malaria', 'published', 'A. Bello', '2025-01-04'::date),
  (2, 'malaria-prevention', 'malaria', 'published', NULL, '2025-01-04'::date),
  (3, 'clearing-stagnant-water', 'malaria', 'published', 'A. Bello', '2025-01-01'::date),
  (4, 'antenatal-visits', 'maternal-health', 'published', 'N. Okoro', '2024-11-30'::date),
  (6, 'eating-well-on-a-budget', 'nutrition', 'published', NULL, '2025-02-10'::date),
  (7, 'iron-rich-foods', 'nutrition', 'draft', 'F. Yusuf', '2025-02-11'::date),
  (8, 'wash-your-hands', 'hygiene', 'published', NULL, '2025-03-01'::date),
  (10, 'safe-drinking-water', 'clean-water', 'published', 'I. Musa', '2025-03-15'::date),
  (11, 'typhoid-and-clean-water', 'clean-water', 'published', 'I. Musa', '2025-03-15'::date),
  (12, 'first-aid-for-burns', 'first-aid', 'published', 'Dr. Ade', '2025-04-02'::date),
  (13, 'choking-help', 'first-aid', 'published', 'Dr. Ade', '2025-04-02'::date),
  (14, 'vaccines-for-children', 'immunisation', 'published', NULL, '2025-04-20'::date),
  (16, 'family-planning-options', 'family-planning', 'published', 'G. Eze', '2025-05-05'::date),
  (17, 'fever-in-children', 'malaria', 'published', NULL, '2025-05-06'::date),
  (18, 'breastfeeding-basics', 'maternal-health', 'published', 'N. Okoro', '2025-05-10'::date),
  (19, 'diarrhoea-and-ors', 'hygiene', 'published', NULL, '2025-05-10'::date),
  (20, 'malaria-in-pregnancy', 'malaria', 'published', 'N. Okoro', NULL),
  (21, 'healthy-snacks-for-children', 'nutrition', 'published', 'F. Yusuf', '2025-06-01'::date),
  (22, 'clean-cooking-and-smoke', 'nutrition', 'published', NULL, '2025-06-02'::date),
  (23, 'first-aid-kit-at-home', 'first-aid', 'draft', 'Dr. Ade', '2025-06-10'::date)
on conflict (id) do update set
  slug = excluded.slug,
  topic_slug = excluded.topic_slug,
  status = excluded.status,
  author = excluded.author,
  source_updated_at = excluded.source_updated_at,
  updated_at = now();

-- Translations (English from health-content.csv, Pidgin from pidgin-translations.csv).
insert into article_translations (article_id, language_code, title, summary, body) values
  (1, 'en', 'Sleeping under a treated net', NULL, 'Sleep under an insecticide-treated net every night to prevent malaria, especially children and pregnant women.'),
  (2, 'en', 'malaria prevention', 'Simple steps to avoid malaria', 'Use treated nets, clear stagnant water, and see a clinic early if you have fever.'),
  (3, 'en', 'CLEARING STAGNANT WATER', 'Mosquitoes breed in still water', 'Empty containers and clear gutters so mosquitoes cannot breed near your home.'),
  (4, 'en', 'Antenatal visits', 'Why to attend antenatal care', 'Attend antenatal check-ups at least four times during pregnancy to keep mother and baby healthy.'),
  (6, 'en', 'Eating well on a budget', 'Balanced meals with local foods', 'Combine beans, vegetables, and grains for a balanced meal without spending much.'),
  (7, 'en', 'Iron-rich foods', 'Iron-rich foods', 'Eat green leafy vegetables and beans to prevent anaemia.'),
  (8, 'en', 'Wash your hands', 'Handwashing prevents disease', 'Wash your hands with soap and clean water before eating and after using the toilet.'),
  (10, 'en', 'Safe drinking water', 'Make water safe to drink', 'Boil or treat water before drinking if you are not sure it is clean.'),
  (11, 'en', 'Typhoid and clean water', NULL, 'Typhoid spreads through dirty water and food. Drink safe water and wash food well.'),
  (12, 'en', 'First aid for burns', 'What to do for a minor burn', 'Cool a minor burn under running water for about twenty minutes. Do not apply oil or toothpaste.'),
  (13, 'en', 'Choking help', NULL, 'For a choking adult, give firm back blows between the shoulder blades and call for help.'),
  (14, 'en', 'Vaccines for children', 'Keep to the vaccine schedule', 'Take your child for all routine vaccines on time to protect against serious diseases.'),
  (16, 'en', 'Family planning options', 'Spacing births safely', 'Talk to a health worker about safe options for spacing your children.'),
  (17, 'en', 'Fever in children', 'When fever is an emergency', 'If a child has fever with fits, fast breathing or cannot drink, go to a clinic immediately.'),
  (18, 'en', 'Breastfeeding basics', 'Breastfeed in the first hour', 'Start breastfeeding within the first hour of birth and feed only breast milk for six months.'),
  (19, 'en', 'DIARRHOEA AND ORS', 'Treat diarrhoea with fluids', 'Give oral rehydration solution (ORS) and continue feeding a child with diarrhoea. Seek help if it does not stop.'),
  (20, 'en', 'Malaria in pregnancy', NULL, 'Pregnant women should sleep under a treated net and take the preventive medicine a clinic gives them.'),
  (21, 'en', 'Healthy snacks for children', 'Better than sugary snacks', 'Offer fruit, groundnuts or boiled eggs instead of sweets and soft drinks.'),
  (22, 'en', 'Clean cooking & smoke', 'Reduce cooking smoke', 'Cook in a well-ventilated place to reduce smoke that can harm the lungs.'),
  (23, 'en', 'First aid kit at home', 'TODO: expand this', 'Keep plasters, clean gauze, antiseptic and ORS at home.'),
  (1, 'pcm', 'Sleep under net wey dem treat', NULL, 'Make you sleep under insecticide-treated net every night to stop malaria, especially pikin and pregnant woman.'),
  (4, 'pcm', 'Antenatal visit', NULL, 'Go clinic for antenatal check-up at least four times when you dey pregnant so mama and pikin go dey healthy.'),
  (6, 'pcm', 'Chop well without spending plenty money', NULL, 'Mix beans, vegetable and grain make you get balanced food without spending plenty money.'),
  (8, 'pcm', 'Wash your hand', NULL, 'Wash your hand with soap and clean water before you chop and after you use toilet.'),
  (10, 'pcm', 'Water wey safe to drink', NULL, 'Boil or treat water before you drink am if you no sure say e clean.'),
  (12, 'pcm', 'First aid for burn', NULL, 'Put small burn under running water for around twenty minutes. No put oil or toothpaste.'),
  (14, 'pcm', 'Vaccine for pikin', NULL, 'Carry your pikin go take all the routine vaccine on time to protect am from serious sickness.'),
  (17, 'pcm', 'Fever for pikin', NULL, 'If pikin get fever with convulsion, fast breathing, or e no fit drink, carry am go clinic sharp sharp.'),
  (18, 'pcm', 'Breastfeeding basics', NULL, 'Start to breastfeed within the first hour after birth and give only breast milk for six months.'),
  (20, 'pcm', 'Malaria when you dey pregnant', NULL, 'Pregnant woman suppose sleep under treated net and take the medicine wey clinic give for malaria prevention.')
on conflict (article_id, language_code) do update set
  title = excluded.title,
  summary = excluded.summary,
  body = excluded.body;

commit;
